# User Settings | Edit there as per required

title: 10sloth08's
url: "http://10sloth08.github.io"
baseurl: "" #/accent

# This will show up at the top of index page
site_heading: >
    경진 <span class="faded">'s blog</span>

email: pokly0908@naver.com
author: 10sloth08
# This description will show up in google search results
# (for index page) etc.
description: >
    홀롤롤롤
    
    

# This will what will show against &copy; in the footer
copyright: accent
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    Welcome! This is <span>accent</span>, a mobile friendly theme for Jekyll. The main feature of this
    theme is that you can change the accent color. Refer the
    <a class="underline different-highlight" href="http://10sloth08.githib.io/documentation.html">
        Documentation
    </a>
    to know how.

permalink: /:title.html

# Comments are powered by disqus
comments: true
disqus-shortname: 10sloth08

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    pokly0908@naver.com, pokly0908@hanyang.ac.kr

about_footer: true

twitter_username: pokly0908
github_username: 10sloth08
facebook_id: 100012011654817

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-69243698-7 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/date1.jpeg" # This will show in facebook thumbnails
twitter_image: "images/date1.jpeg" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

plugins:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
